---
kind: pipeline
name: default

steps:
- name: docker-release
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USER
    password:
      from_secret: DOCKER_PASSWORD
    repo: gomods/athens
    tags:
      - ${DRONE_TAG}
      - latest
    dockerfile: cmd/proxy/Dockerfile
    build_args:
      - VERSION=${DRONE_TAG}

  when:
    event:
      - tag

- name: publish-helm
  image: gomods/drone-helm
  settings:
    charts_repo: https://athens.blob.core.windows.net
  environment:
    AZURE_STORAGE_CONNECTION_STRING:
      from_secret: AZURE_STORAGE_CONNECTION_STRING
  when:
    branch:
      - main
    event:
     - push

# Here we can add any backend storage that can be tested.
services:

volumes:
  - name: cache
    temp: {}
---
kind: signature
hmac: 8ee2a04fedfd1a0c1ab3da19a3441485bf447de3e04fe057f626c83454a042b6

...
