kind: pipeline
name: default

steps:
- name: build
  image: golang:1.12rc1
  commands:
  # wait for services to be ready.
  - sleep 3 

  # build
  - go build -mod=vendor cmd/proxy/*.go

  # test
  - ./scripts/check_gofmt.sh
  - go vet -mod=vendor ./...
  - go test -mod=vendor -v ./...
  - ./scripts/test_e2e.sh
  environment:
    GO111MODULE: on
    ATHENS_MONGO_STORAGE_URL: mongodb://mongo:27017
    ATHENS_MINIO_ENDPOINT: minio:9000
  when:
    event:
      - push
      - pull_request

services:
- name: mongo
  image: mongo
  ports:
  - 27017
- name: minio
  image: minio/minio:latest
  command:
    - server
    - /data
  ports:
    - 9000
  environment:
    MINIO_ACCESS_KEY: minio
    MINIO_SECRET_KEY: minio123
