services:
  - mongodb
  - postgresql
language: go
install: false
go:
  - "1.10.x"
script:
  - test -z $(gofmt -s -l $GO_FILES)         # Fail if a .go file hasn't been formatted with gofmt
  - go vet ./...                             # Go static analyzer
  - golint -set_exit_status $(go list ./...) # Linter
  - go test -race ./...                      # Run all the tests with the race detector enabled
before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/) # All the .go files, excluding vendor/
  - go get github.com/golang/lint/golint
  - export POP_PATH=$PWD/cmd/proxy
  - export GO_ENV=test_postgres
  - export MINIO_ACCESS_KEY=minio
  - export MINIO_SECRET_KEY=minio123
  - export ATHENS_MONGO_STORAGE_URL=mongodb://127.0.0.1:27017
  - wget https://dl.minio.io/server/minio/release/linux-amd64/minio && chmod +x minio && nohup ./minio server . &
  - go get -u -v github.com/gobuffalo/buffalo/buffalo
  - go get -u -v golang.org/x/vgo
  - buffalo db create
  - buffalo db migrate up
