build: off

clone_folder: c:\gopath\src\github.com\gomods\athens

environment:
  GOPATH: c:\gopath
  GO111MODULE: on
  GOPROXY: https://proxy.golang.org

stack: go 1.12

test_script:
  - go test ./...