build: off

clone_folder: c:\gopath\src\github.com\gomods\athens

image: Previous Visual Studio 2019

environment:
  GOPATH: c:\gopath
  GO111MODULE: on
  GOPROXY: https://proxy.golang.org
  SKIP_UNTIL_113: true
  USE_DEFAULT_CONFIG: true
  SKIP_POSTGRES: true
  SKIP_MYSQL: true
  SKIP_ETCD: true
  SKIP_MINIO: true
  SKIP_MONGO: true
  SKIP_AZURITE: true
  SKIP_REDIS: true
  SKIP_PROTECTEDREDIS: true

stack: go 1.14

test_script:
  - go version
  - go test ./...

