# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

pool:
  vmImage: 'win1803'

steps:
- script: |
    docker-compose -f docker-compose.yml -p athensunit up --exit-code-from=testunit-win --build testunit-win
  displayName: 'Unit tests'

