# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

pool:
  vmImage: 'win1803'

variables:
  acrRegistryName: 'gomods'

steps:
- powershell: |
    choco install azure-cli
    # acr login
    & "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" login --service-principal -u $(acr-appId) -p $(acr-password) --tenant $(acr-tenant)
    & "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" acr login --name $(acrRegistryName)
    docker-compose -p athensunit up --exit-code-from=testunit-win --build testunit-win
  displayName: 'Unit tests'

