# # GoBinary returns the path to the go binary to use. This value can be a name on the PATH, or the full path
# # Defaults to "go"
# # Env override: GO_BINARY_PATH
# GoBinary = "go"

# # Supported values are: 'development' and 'production'. Defaults to "development"
# # Env override: GO_ENV
# GoEnv = "development"

# # LogLevel returns the system's exposure to internal logs. Defaults to debug.
# # Env override: ATHENS_LOG_LEVEL
# LogLevel = "debug"

# # CloudRuntime is the Cloud Provider on which the Proxy/Registry is running.
# # Defaults to "none"
# # Env override: ATHENS_CLOUD_RUNTIME
# CloudRuntime = "none"

# # MaxConcurrency sets maximum level of concurrency
# # Defaults to number of cores if not specified.
# # Env override: ATHENS_MAX_CONCURRENCY
# MaxConcurrency = 0

# # The maximum number of failures for jobs submitted to buffalo workers
# # Defaults to 5.
# # Env override: ATHENS_WORKER_MAX_FAILS
# MaxWorkerFails = 5

# # The filename for the include exclude filter. Defaults to 'filter.conf'
# # Env override: ATHENS_FILTER_FILENAME 
# FilterFile = "filter.conf"

# # Timeout is the timeout for external network calls. 
# # This value is used as the default for storage backends if they don't specify timeouts
# # Defaults to 300
# # Env override: ATHENS_TIMEOUT
# TimeoutSeconds = 300

# # EnableCSRFProtection determines whether to enable CSRF protection.
# # Defaults to false
# # Env override: ATHENS_ENABLE_CSRF_PROTECTION
# EnableCSRFProtection = false


# [Proxy]
#     # Possible values are memory, disk, mongo, postgres, sqlite, cockroach, mysql
#     # Defaults to mongo
#     # Env override: ATHENS_STORAGE_TYPE
#     StorageType = ""
#     # Env override: PORT
# 	Port = ""
#     # Env override: OLYMPUS_GLOBAL_ENDPOINT
#     OlympusGlobalEndpoint = ""
#     # Redis queue for buffalo workers
#     # Defaults to ":6379"
#     # Env override: ATHENS_REDIS_QUEUE_PORT
# 	RedisQueueAddress     = ""

# [Olympus]
#     # Possible values are memory, disk, mongo, postgres, sqlite, cockroach, mysql
#     # Defaults to memory
#     # Env override: ATHENS_STORAGE_TYPE
#     StorageType = ""
#     # Env override: PORT
# 	Port = ""
#     # Background worker type. Defaults to redis
#     # Env override: OLYMPUS_BACKGROUND_WORKER_TYPE
#     WorkerType = ""
#     # Redis queue for buffalo workers
#     # Defaults to ":6379"
#     # Env override: OLYMPUS_REDIS_QUEUE_PORT
#     RedisQueueAddress = ""

# [Storage]
#     [Storage.CDN]
#         # Env override: CDN_ENDPOINT
#         Endpoint = ""
#         # Defaults to Global Timeout
#         TimeoutSeconds = 30
#     [Storage.Disk]
#         # RootPath is the Athens Disk Root folder 
#         # Env override: ATHENS_DISK_STORAGE_ROOT
#         RootPath = ""
#         # Defaults to Global Timeout
#         TimeoutSeconds = 30
#     [Storage.GCP]
#         # Env overide: GOOGLE_CLOUD_PROJECT
#         ProjectID = ""
#         # Env override: ATHENS_STORAGE_GCP_BUCKET
# 	    Bucket = ""
#         # Defaults to Global Timeout
#         TimeoutSeconds = 30
#     [Storage.Minio]
#         # Env override: ATHENS_MINIO_ENDPOINT
#         Endpoint = ""
#         # Env override: ATHENS_MINIO_ACCESS_KEY_ID
#         Key = ""
#         # Env override: ATHENS_MINIO_SECRET_ACCESS_KEY
#         Secret = ""
#         # Defaults to Global Timeout
#         TimeoutSeconds = 30
#         # Defaults to true
#         # Env override: ATHENS_MINIO_USE_SSL
#         EnableSSL = true
#         # Defaults to gomods
#         # Env override: ATHENS_MINIO_BUCKET_NAME
#         Bucket = "gomods"
#     [Storage.Mongo]
#         # Env override: ATHENS_MONGO_STORAGE_URL
#         URL = ""
#         # Env override: MONGO_USER
#         User = ""
#         # Env override: MONGO_PASSWORD
#         Password = ""
#         # Defaults to Global Timeout
#         # Env override: MONGO_CONN_TIMEOUT_SEC
#         TimeoutSeconds = 30
#     [Storage.RDBMS]
#         # Env override: ATHENS_RDBMS_STORAGE_NAME
#         Name = ""
#         # Defaults to Global Timeout
#         TimeoutSeconds = 30
