version: '3'
services:
  mongo:
    image: mongo:3.0.15-wheezy
    ports:
      - 27017:27017
  mysql:
    image: bitnami/mysql:5.7.21-r7
    ports:
      - "3306:3306"
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_USER=vgp"
      - "MYSQL_PASSWORD=vgp"
      - "MYSQL_DATABASE=vgoprox"
  jaeger:
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9441
    image: jaegertracing/all-in-one:latest
    ports:
      - 14268:14268
      - 9411:9411
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
