version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: cmd/proxy/Dockerfile
    environment:
      - ATHENS_MONGO_STORAGE_URL=mongodb://127.0.0.1:27017
      - TIMEOUT=2
      # - ATHENS_STORAGE_TYPE=mongo
      - ATHENS_STORAGE_TYPE=memory
    ports:
      - 3000:3000
    depends_on:
      - mongo
    networks:
      - mongo
  mongo:
    image: mongo:3.7.9-jessie
    ports:
      - 27017:27017
    networks:
      - mongo
  minio:
    image: minio/minio:latest
    command: server /data
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
  datadog:
    environment:
      - DD_API_KEY=
      - DD_LOG_LEVEL=trace
      - DD_APM_ENABLED=true
    image:
      datadog/agent:latest
    ports:
      - 8126:8126
  jaeger:
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9441
    image: jaegertracing/all-in-one:latest
    ports:
      - 14268:14268
      - 9411:9411
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
networks:
  mongo:
    driver: bridge
    internal: false
