development:
  dialect: "postgres"
  database: athens
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: postgres

test:
  dialect: "postgres"
  database: athens_test
  user: postgres
  password: postgres
  port: 5432
  host: 127.0.0.1
  pool: 5

production:
  dialect: "postgres"
  database: olympusdb
  host: {{ env "DB_HOST" }}
  port: {{ env "DB_PORT" }}
  user: {{ env "DB_USER" }}
  password: {{ env "DB_PASS" }}
