{{- if .Values.goCenter.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-gocenter
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  FilterForGoCenter: |-
    # FilterFile for fetching modules directly from https://gocenter.io
    D
{{- end -}}
