version: '3'
services:
  mongo:
    image: mongo:3.7.9-jessie
    ports:
      - 27017:27017
    networks:
      - mongo
  proxy:
    image: gopackages/proxy
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      - "ATHENS_MONGO_STORAGE_URL=mongodb://mongo:27017"
    networks:
      - mongo
networks:
  mongo:
