#
#	Used to optionally provide support for mTLS
#
version: '3'

services:

  nginx:
    image: nginx:latest
    depends_on: [dev]
    volumes:
    - ./mtls/nginx/conf.d:/etc/nginx/conf.d
    - ./mtls/certs:/etc/nginx/mtls_certs
    ports:
      - "443:443"
